In [1]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np 
import pandas as pd

In [2]:
train =pd.read_csv("/kaggle/input/aification/train.csv") 
test = pd.read_csv("/kaggle/input/aification/test.csv")

In [3]:
train.head()

,id,bangla_question,english_question
0,1,25 kg ভরের বস্তুর গতিশক্তি 450 J হলে বেগ কত?,What is the velocity if the kinetic energy of ...
1,2,একটি বস্তু 40 m/s বেগে চলছে। 8 m/s² মন্দনে কত ...,An object is moving at 40 m/s velocity. In how...
2,3,একটি প্রোটনের ভর 9.11×10⁻³¹ kg হলে এর শক্তি কত...,If the mass of a proton is 9.11×10⁻³¹ kg; what...
3,4,একটি বস্তু 70 m/s বেগে চলছে। 2 m/s² মন্দনে কত ...,An object is moving at 70 m/s velocity. In how...
4,5,44 kg ভরের একটি গাড়ি 55 m/s বেগে চলছে এবং 18 ...,A car of mass 44 kg is moving at 55 m/s veloci...

In [4]:
train.tail()

,id,bangla_question,english_question
4995,4996,একটি সমান্তর অনুক্রমের প্রথম পদ 23 এবং সাধারণ ...,The first term of an arithmetic progression is...
4996,4997,59 g NaOH এবং 62 g HCl বিক্রিয়া করে NaCl উৎপন...,59 g NaOH and 62 g HCl react to produce NaCl. ...
4997,4998,একটি ইন্ডাকটরে ৬ H প্রতিবাদকতা এবং ৯০ Hz ফ্রিক...,An inductor has an inductance of 6 H and a fre...
4998,4999,একটি দ্বিঘাত সমীকরণ 3x² + -18x + -216 = 0 এর ব...,Find the real roots of the quadratic equation ...
4999,5000,322K তাপমাত্রার একটি সিস্টেম থেকে 3220 J তাপ শ...,If a system at 322K temperature absorbs 3220 J...

In [5]:
test.head()

   id                                    bangla_question
0   1           রক্তচাপ 115/80 mmHg হলে পালস প্রেসার কত?
1   2  150 J কাজ করে একটি বস্তুকে 20 m দূরত্বে স্থানা...
2   3  একটি আয়তক্ষেত্রের দৈর্ঘ্য 21 cm এবং প্রস্থ 30...
3   4  DNA অণুতে যদি অ্যাডেনিন 36% থাকে, তাহলে থাইমিন...
4   5  45 g CH₃COOH এ কতগুলি মোল পদার্থ আছে? (আণবিক ভ...

# Data Cleaning

In [6]:
import re
def clean(text):
  text = re.sub(r"\s+"," ", text).strip()
  return text

In [7]:
train['bangla_question'] = train['bangla_question'].apply(clean)
train['english_question'] = train['english_question'].apply(clean)

In [8]:
train.head()

,id,bangla_question,english_question
0,1,25 kg ভরের বস্তুর গতিশক্তি 450 J হলে বেগ কত?,What is the velocity if the kinetic energy of ...
1,2,একটি বস্তু 40 m/s বেগে চলছে। 8 m/s² মন্দনে কত ...,An object is moving at 40 m/s velocity. In how...
2,3,একটি প্রোটনের ভর 9.11×10⁻³¹ kg হলে এর শক্তি কত...,If the mass of a proton is 9.11×10⁻³¹ kg; what...
3,4,একটি বস্তু 70 m/s বেগে চলছে। 2 m/s² মন্দনে কত ...,An object is moving at 70 m/s velocity. In how...
4,5,44 kg ভরের একটি গাড়ি 55 m/s বেগে চলছে এবং 18 ...,A car of mass 44 kg is moving at 55 m/s veloci...

In [9]:
#remove rows with missing translation
train = train.dropna(subset = ["bangla_question", "english_question"])

train["bangla_question"] = train["bangla_question"].astype(str)
train["english_question"] = train["english_question"].astype(str)

In [10]:
#remove very small strings
train = train[train["bangla_question"].str.len() > 5]
train = train[train["english_question"].str.len() > 5]

# Split into Train / Validation (dev)

In [11]:
train = train.sample(frac = 1, random_state = 42).reset_index(drop = True)
train_set = train.iloc[:4_000]
dev_set = train.iloc[4_000:5_000]

train_set[["english_question", "bangla_question"]].to_csv("train.tsv", sep = "\t", index = False, header = False)
dev_set[["english_question", "bangla_question"]].to_csv("dev.tsv", sep = "\t", index = False, header = False)

In [12]:
!cat train.tsv dev.tsv > combined.txt

# SentencePiece BPE Tokenizer

In [13]:
import sentencepiece as spm
spm.SentencePieceTrainer.train(
    input = "combined.txt",
    model_prefix = "en_bn_spm",
    vocab_size = 8_000,
    model_type = "bpe",
    character_coverage = 1.0,
    unk_id = 0, pad_id = 1, bos_id = 2, eos_id = 3,
    user_defined_symbols="<en>,<bn>",
    normalization_rule_name="nmt_nfkc",
    split_digits=True,
    byte_fallback=True
)

print("Tokenizer trained to en_bn_spm.model")

Tokenizer trained to en_bn_spm.model

sentencepiece_trainer.cc(78) LOG(INFO) Starts training with :
trainer_spec {
  input: combined.txt
  input_format:
  model_prefix: en_bn_spm
  model_type: BPE
  vocab_size: 8000
  self_test_sample_size: 0
  character_coverage: 1
  input_sentence_size: 0
  shuffle_input_sentence: 1
  seed_sentencepiece_size: 1000000
  shrinking_factor: 0.75
  max_sentence_length: 4192
  num_threads: 16
  num_sub_iterations: 2
  max_sentencepiece_length: 16
  split_by_unicode_script: 1
  split_by_number: 1
  split_by_whitespace: 1
  split_digits: 1
  pretokenization_delimiter:
  treat_whitespace_as_suffix: 0
  allow_whitespace_only_pieces: 0
  user_defined_symbols: <en>
  user_defined_symbols: <bn>
  required_chars:
  byte_fallback: 1
  vocabulary_output_piece_score: 1
  train_extremely_large_corpus: 0
  seed_sentencepieces_file:
  hard_vocab_limit: 1
  use_all_vocab: 0
  unk_id: 0
  bos_id: 2
  eos_id: 3
  pad_id: 1
  unk_piece: <unk>
  bos_piece: <s>
  eos_piece: </s>
  pad_piece: <pad>
  unk_surface:  ⁇
  enable_differential_privacy: 0
  differential_privacy_noise_level: 0
  differential_privacy_clipping_threshold: 0
}
normalizer_spec {
  name: nmt_nfkc
  add_dummy_prefix: 1
  remove_extra_whitespaces: 1
  escape_whitespaces: 1
  normalization_rule_tsv:
}
denormalizer_spec {}
trainer_interface.cc(353) LOG(INFO) SentenceIterator is not specified. Using MultiFileSentenceIterator.
trainer_interface.cc(185) LOG(INFO) Loading corpus: combined.txt
trainer_interface.cc(409) LOG(INFO) Loaded all 5000 sentences
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <unk>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <pad>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <s>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: </s>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <en>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <bn>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x00>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x01>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x02>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x03>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x04>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x05>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x06>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x07>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x08>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x09>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x0A>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x0B>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x0C>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x0D>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x0E>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x0F>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x10>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x11>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x12>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x13>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x14>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x15>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x16>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x17>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x18>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x19>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x1A>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x1B>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x1C>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x1D>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x1E>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x1F>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x20>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x21>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x22>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x23>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x24>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x25>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x26>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x27>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x28>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x29>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x2A>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x2B>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x2C>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x2D>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x2E>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x2F>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x30>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x31>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x32>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x33>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x34>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x35>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x36>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x37>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x38>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x39>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x3A>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x3B>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x3C>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x3D>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x3E>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x3F>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x40>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x41>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x42>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x43>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x44>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x45>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x46>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x47>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x48>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x49>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x4A>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x4B>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x4C>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x4D>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x4E>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x4F>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x50>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x51>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x52>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x53>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x54>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x55>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x56>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x57>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x58>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x59>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x5A>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x5B>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x5C>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x5D>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x5E>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x5F>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x60>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x61>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x62>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x63>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x64>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x65>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x66>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x67>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x68>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x69>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x6A>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x6B>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x6C>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x6D>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x6E>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x6F>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x70>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x71>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x72>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x73>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x74>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x75>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x76>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x77>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x78>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x79>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x7A>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x7B>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x7C>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x7D>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x7E>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x7F>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x80>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x81>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x82>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x83>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x84>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x85>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x86>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x87>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x88>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x89>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x8A>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x8B>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x8C>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x8D>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x8E>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x8F>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x90>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x91>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x92>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x93>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x94>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x95>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x96>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x97>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x98>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x99>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x9A>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x9B>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x9C>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x9D>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x9E>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0x9F>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xA0>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xA1>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xA2>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xA3>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xA4>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xA5>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xA6>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xA7>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xA8>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xA9>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xAA>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xAB>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xAC>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xAD>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xAE>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xAF>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xB0>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xB1>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xB2>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xB3>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xB4>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xB5>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xB6>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xB7>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xB8>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xB9>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xBA>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xBB>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xBC>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xBD>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xBE>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xBF>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xC0>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xC1>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xC2>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xC3>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xC4>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xC5>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xC6>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xC7>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xC8>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xC9>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xCA>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xCB>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xCC>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xCD>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xCE>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xCF>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xD0>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xD1>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xD2>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xD3>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xD4>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xD5>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xD6>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xD7>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xD8>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xD9>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xDA>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xDB>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xDC>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xDD>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xDE>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xDF>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xE0>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xE1>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xE2>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xE3>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xE4>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xE5>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xE6>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xE7>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xE8>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xE9>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xEA>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xEB>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xEC>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xED>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xEE>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xEF>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xF0>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xF1>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xF2>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xF3>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xF4>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xF5>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xF6>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xF7>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xF8>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xF9>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xFA>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xFB>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xFC>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xFD>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xFE>
trainer_interface.cc(425) LOG(INFO) Adding meta_piece: <0xFF>
trainer_interface.cc(430) LOG(INFO) Normalizing sentences...
trainer_interface.cc(539) LOG(INFO) all chars count=1107766
trainer_interface.cc(560) LOG(INFO) Alphabet size=187
trainer_interface.cc(561) LOG(INFO) Final character coverage=1
trainer_interface.cc(592) LOG(INFO) Done! preprocessed 5000 sentences.
trainer_interface.cc(598) LOG(INFO) Tokenizing input sentences with whitespace: 5000
trainer_interface.cc(609) LOG(INFO) Done! 6619
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=14438 min_freq=14
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=5348 size=20 all=2287 active=1349 piece=er
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=3507 size=40 all=2638 active=1700 piece=▁এক
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2457 size=60 all=3099 active=2161 piece=▁k
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=2019 size=80 all=3340 active=2402 piece=▁ফলন
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1651 size=100 all=3694 active=2756 piece=াক
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=1636 min_freq=52
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1331 size=120 all=4039 active=1310 piece=▁ob
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1166 size=140 all=4239 active=1510 piece=▁co
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=1049 size=160 all=4437 active=1708 piece=▁di
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=940 size=180 all=4631 active=1902 piece=▁গা
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=869 size=200 all=4715 active=1986 piece=ation
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=868 min_freq=50
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=805 size=220 all=4881 active=1148 piece=▁it
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=726 size=240 all=4988 active=1255 piece=▁মো
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=684 size=260 all=5087 active=1354 piece=▁dec
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=651 size=280 all=5158 active=1425 piece=ject
bpe_model_trainer.cc(268) LOG(INFO) Added: freq=599 size=300 all=5288 active=1555 piece=▁first
bpe_model_trainer.cc(159) LOG(INFO) Updating active symbols. max_freq=599 min_freq=42

# HF Dataset + Tokenization

## Load NLLB-200 distilled (600 M)

In [14]:
!pip install -U transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.53.3)
Collecting transformers
  Downloading transformers-4.57.1-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 1.3 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.19.1)
Collecting huggingface-hub<1.0,>=0.34.0 (from transformers)
  Downloading huggingface_hub-0.36.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2025.9.18)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.5)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Downloading tokenizers-0.22.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.1.10)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17->transformers) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17->transformers) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17->transformers) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17->transformers) (2025.2.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17->transformers) (2022.2.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17->transformers) (2.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.8.3)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.17->transformers) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.17->transformers) (2022.2.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy>=1.17->transformers) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy>=1.17->transformers) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy>=1.17->transformers) (2024.2.0)
Downloading transformers-4.57.1-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 91.7 MB/s eta 0:00:00
Downloading huggingface_hub-0.36.0-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.1/566.1 kB 22.8 MB/s eta 0:00:00
Downloading tokenizers-0.22.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 74.8 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, tokenizers, transformers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 1.0.0rc2
    Uninstalling huggingface-hub-1.0.0rc2:
      Successfully uninstalled huggingface-hub-1.0.0rc2
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.21.2
    Uninstalling tokenizers-0.21.2:
      Successfully uninstalled tokenizers-0.21.2
  Attempting uninstall: transformers
    Found existing installation: transformers 4.53.3
    Uninstalling transformers-4.53.3:
      Successfully uninstalled transformers-4.53.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 4.1.1 requires pyarrow>=21.0.0, but you have pyarrow 19.0.1 which is incompatible.
gradio 5.38.1 requires pydantic<2.12,>=2.0, but you have pydantic 2.12.0a1 which is incompatible.
Successfully installed huggingface-hub-0.36.0 tokenizers-0.22.1 transformers-4.57.1

In [15]:
from datasets import load_dataset
from transformers import AutoTokenizer
from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer, DataCollatorForSeq2Seq

model_name = "facebook/nllb-200-distilled-600M"
tokenizer = AutoTokenizer.from_pretrained(
    model_name,
    src_lang="eng_Latn",
    tgt_lang="ben_Beng",
    use_fast=False,
    use_default_chat_template=False,
)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/564 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/4.85M [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/17.3M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/846 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

In [16]:
#Load tsv
data_files = {"train": "train.tsv", "validation": "dev.tsv"}
raw = load_dataset(
    "csv",
    data_files = data_files,
    delimiter = "\t",
    column_names = ["en", "bn"]
)

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

In [17]:
def preprocess(ex):
    #src = bengali, target = english
    inputs = tokenizer(
        ex["bn"],
        max_length = 128,
        truncation = True
    )
    with tokenizer.as_target_tokenizer():
        targets = tokenizer(
            ex["en"],
            max_length = 128,
            truncation = True
        )
    inputs["labels"] = targets["input_ids"]
    return inputs

tokenized = raw.map(
    preprocess,
    batched = True,
    remove_columns = ["en","bn"]
)

print(tokenized)

Map:   0%|          | 0/4000 [00:00<?, ? examples/s]

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 4000
    })
    validation: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 1000
    })
})

# Fine-tune NLLB

In [18]:
#model = AutoModelForSeq2SeqLM.from_pretrained("facebook/nllb-200-distilled-600M")
model.resize_token_embeddings(len(tokenizer))

M2M100ScaledWordEmbedding(256204, 1024, padding_idx=1)

In [19]:
data_collator = DataCollatorForSeq2Seq(
    tokenizer,
    padding = True
)

args = Seq2SeqTrainingArguments(
    output_dir = "./bn_en_nllb",
    eval_strategy = "epoch",
    learning_rate = 5e-5,
    per_device_train_batch_size = 8,
    per_device_eval_batch_size=8,
    weight_decay=0.01,
    save_total_limit=2,
    num_train_epochs=2,           # change to 3 later
    predict_with_generate=True,
    fp16=True,
    logging_steps=200,
    report_to="none",
    save_strategy="epoch",
    load_best_model_at_end=True
)

trainer = Seq2SeqTrainer(
    model = model,
    args = args,
    train_dataset = tokenized["train"],
    eval_dataset = tokenized["validation"],
    tokenizer = tokenizer,
    data_collator = data_collator
)

# Final Trainerrrrrrrrr 🎉🎉

In [20]:
trainer.train()

There were missing keys in the checkpoint model loaded: ['model.encoder.embed_tokens.weight', 'model.decoder.embed_tokens.weight', 'lm_head.weight'].

TrainOutput(global_step=500, training_loss=0.18503855514526368, metrics={'train_runtime': 891.5073, 'train_samples_per_second': 8.974, 'train_steps_per_second': 0.561, 'total_flos': 1366562617688064.0, 'train_loss': 0.18503855514526368, 'epoch': 2.0})

# Translate Test set

In [21]:
english_token = "eng_Latn"
if english_token in tokenizer.get_vocab():
    english_token_id = tokenizer.convert_tokens_to_ids(english_token)
    print(f"Found {english_token} -> ID: {english_token_id}")
else:
    raise ValueError("English token 'eng_Latn' not in tokenizer vocabulary!")

Found eng_Latn -> ID: 256047

In [22]:
test["english_question"] = "" #placeholder
def translate_batch(batch):
    inputs = tokenizer(
        batch["bangla_question"],
        return_tensors="pt",
        padding=True,
        truncation=True, 
        max_length=128
    ).to(model.device)

    generated = model.generate(
        **inputs,
        forced_bos_token_id=english_token_id,
        max_length=128,
        num_beams=5
    )

    decoded_translation = tokenizer.decode(generated[0], skip_special_tokens=True)
    batch["english_question"] = decoded_translation
    
    return batch

test = test.apply(translate_batch, axis=1)

In [23]:
test.head()

,id,bangla_question,english_question
0,1,রক্তচাপ 115/80 mmHg হলে পালস প্রেসার কত?,What is the pulse pressure at 115/80 mmHg?
1,2,150 J কাজ করে একটি বস্তুকে 20 m দূরত্বে স্থানা...,How much newtonian force is required to move a...
2,3,একটি আয়তক্ষেত্রের দৈর্ঘ্য 21 cm এবং প্রস্থ 30...,If the length of a rectangle is 21 cm and the ...
3,4,"DNA অণুতে যদি অ্যাডেনিন 36% থাকে, তাহলে থাইমিন...",If 36% adenin is present in a DNA molecule; wh...
4,5,45 g CH₃COOH এ কতগুলি মোল পদার্থ আছে? (আণবিক ভ...,How many moles of matter are there in 45 g CH3...

In [24]:
test[["id","english_question"]].to_csv("submission.csv", index = False)
print("Submission.csv ready for ZeroAuth 🎉")

Submission.csv ready for ZeroAuth 🎉